baseURL = "https://plan4better.de/"
languageCode = "en-us"
title = "Plan4Better"
[languages.de]
contentDir = "content/de"
title = "Plan4Better"
weight = 2
[[languages.de.menu.center]]
name = "GOAT"
url = "/"
weight = 1
[languages.de.menu.center.params]
heading = "Geo Open Accessibility Tool - GOAT"
text = "GOAT ist ein interaktives Webtool für die Erstellung von Erreichbarkeitsanalysen für den Fuß- und Radverkehr. Detaillierte Infos finden Sie auf den folgenden Seiten."
[[languages.de.menu.center]]
name = "Was ist GOAT?"
parent = "GOAT"
url = "/was-ist-goat/"
weight = 2
[[languages.de.menu.center]]
name = "GOAT-live"
parent = "GOAT"
url = "/goatlive/"
weight = 3
[[languages.de.menu.center]]
name = "Videos"
parent = "GOAT"
url = "/videos/"
weight = 4
[[languages.de.menu.center]]
name = "Tutorials"
parent = "GOAT"
url = "/tutorials/isochrone/"
weight = 5
[[languages.de.menu.center]]
name = "Docs"
parent = "GOAT"
url = "/docs/background/"
weight = 6
[[languages.de.menu.center]]
name = "Competences"
weight = 2
[languages.de.menu.center.params]
heading = "Duis aute irure dolor2"
hidden = true
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua2."
[[languages.de.menu.center]]
name = "Competences Overview"
parent = "Competences"
url = "/competences-overview/"
weight = 2
[[languages.de.menu.center]]
name = "Web-GIS"
parent = "Competences"
url = "/web-gis/"
weight = 3
[[languages.de.menu.center]]
name = "Trainings"
parent = "Competences"
url = "/trainings/"
weight = 4
[[languages.de.menu.center]]
name = "Consultancy"
parent = "Competences"
url = "/consultancy/"
weight = 5
[[languages.de.menu.center]]
name = "Blog"
url = ""
weight = 3
[[languages.de.menu.center]]
name = "Team"
url = ""
weight = 4
[[languages.de.menu.center]]
name = "Kontakt"
url = ""
weight = 5
[[languages.de.menu.footer]]
name = "Team"
url = "/team/"
weight = 1
[[languages.de.menu.footer]]
name = "Kontakt"
url = "/kontakt/"
weight = 2
[[languages.de.menu.footer]]
name = "Imprint & Privacy"
url = "/imprint-privacy/"
weight = 3
[[languages.de.menu.right]]
name = "GOAT testen"
url = "/goatlive/"
weight = 1
[languages.de.menu.right.params]
button = "primary-outline"
[[languages.de.menu.social]]
name = "Twitter"
url = "#"
weight = 1
[languages.de.menu.social.params]
icon = "twitter"
[[languages.de.menu.social]]
name = "Linkedin"
url = "#"
weight = 2
[languages.de.menu.social.params]
icon = "linkedin"
[[languages.de.menu.social]]
name = "GitHub"
url = "#"
weight = 3
[languages.de.menu.social.params]
icon = "github"
[languages.en]
contentDir = "content/en"
title = "Plan4Better"
weight = 1
[[languages.en.menu.center]]
name = "GOAT"
url = ""
weight = 1
[languages.en.menu.center.params]
heading = "Geo Open Accessibility Tool - GOAT"
text = "GOAT is an interactive webtool for accessibility analysis on walking and cycling. Find out more by visiting the subpages."
[[languages.en.menu.center]]
name = "What is GOAT?"
parent = "GOAT"
url = "/what-is-goat/"
weight = 2
[[languages.en.menu.center]]
name = "GOAT-live"
parent = "GOAT"
url = "/goatlive/"
weight = 3
[[languages.en.menu.center]]
name = "Videos"
parent = "GOAT"
url = "/videos/"
weight = 4
[[languages.en.menu.center]]
name = "Tutorials"
parent = "GOAT"
url = "/tutorials/isochrone/"
weight = 5
[[languages.en.menu.center]]
name = "Docs"
parent = "GOAT"
url = "/docs/background/"
weight = 6
[[languages.en.menu.center]]
name = "Competences"
weight = 2
[languages.en.menu.center.params]
heading = "Duis aute irure dolor2"
hidden = true
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua2."
[[languages.en.menu.center]]
name = "Heading 3"
parent = "Competences"
weight = 1
[[languages.en.menu.center]]
name = "Competences Overview"
parent = "Competences"
url = "/competences-overview/"
weight = 2
[[languages.en.menu.center]]
name = "Web-GIS"
parent = "Competences"
url = "/web-gis/"
weight = 3
[[languages.en.menu.center]]
name = "Trainings"
parent = "Competences"
url = "/trainings/"
weight = 4
[[languages.en.menu.center]]
name = "Consultancy"
parent = "Competences"
url = "/consultancy/"
weight = 5
[[languages.en.menu.center]]
name = "Heading 4"
parent = "Competences"
pre = "2"
weight = 6
[[languages.en.menu.center]]
name = "Link 4"
parent = "Competences"
pre = "2"
url = "/link4/"
weight = 7
[[languages.en.menu.center]]
name = "Link 5"
parent = "Competences"
pre = "2"
url = "/link5/"
weight = 8
[[languages.en.menu.center]]
name = "Link 6"
parent = "Competences"
pre = "2"
url = "/link6/"
weight = 9
[[languages.en.menu.center]]
name = "Blog"
url = ""
weight = 3
[[languages.en.menu.center]]
name = "Team"
url = ""
weight = 4
[[languages.en.menu.center]]
name = "Contact"
url = ""
weight = 5
[[languages.en.menu.footer]]
name = "Team"
url = "/team/"
weight = 1
[[languages.en.menu.footer]]
name = "Contact us"
url = "/contact/"
weight = 2
[[languages.en.menu.footer]]
name = "Imprint & Privacy"
url = "/imprint-privacy/"
weight = 3
[[languages.en.menu.right]]
name = "Try GOAT"
url = "/goatlive/"
weight = 1
[languages.en.menu.right.params]
button = "primary-outline"
[[languages.en.menu.social]]
name = "Twitter"
url = "https://twitter.com/GoatTool"
weight = 1
[languages.en.menu.social.params]
icon = "twitter"
[[languages.en.menu.social]]
name = "Linkedin"
url = "https://www.linkedin.com/company/goat-tool/"
weight = 2
[languages.en.menu.social.params]
icon = "linkedin"
[[languages.en.menu.social]]
name = "GitHub"
url = "https://github.com/goat-community/"
weight = 3
[languages.en.menu.social.params]
icon = "github"
[markup.highlight]
style = "monokai"
[markup.tableOfContents]
endLevel = 2
startLevel = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]
[params]
address = "Augustenstraße 49 <br>80333 München <br>Germany"
email = "info@plan4better.de"
mailchimp_form_action = ""
mailchimp_hidden_name = ""
phone = "+49 89 2000 708 30"
site_logo = "images/logo.png"
site_logo_light = "images/logo-light.png"
[params.banner.de]
text = "Wird derzeit gewartet."
[params.banner.en]
text = "Currently under maintenance."
[taxonomies]
author = "author"
categories = "categories"
