---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Config
  match: "**/*"
- type: directory
  path: content/en
  label: Pages EN
  create: documents
  match: "*"
  templates:
  - blocks
- type: directory
  path: content/de
  label: Pages DE
  create: documents
  match: "*"
  templates:
  - blocks
- type: directory
  path: content/en/posts
  label: Posts EN
  create: documents
  match: "**/*"
- type: directory
  path: content/de/posts
  label: Posts DE
  create: documents
  match: "**/*"
- type: document
  path: data/authors.yml
  label: Authors
- type: document
  path: data/videos.yml
  label: Videos
- type: document
  path: data/live.yml
  label: GOATlive
- type: document
  path: data/docs.yml
  label: Docs Categories
- type: document
  path: data/tutorials.yml
  label: Tutorial Categories
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
